Forward port of GBPTree consistency check from 3.5
Original PR: Consistency check now verify structural consistency
of indexesGBPTree consistency check

** Check structural consistency of schema indexes **
Before comparing content of index to store we do a structural
consistency check on the index itself, making sure that keys are ordered,
tree pointers make sense and no pages have leaked. If index is not
consistent the inconsistencies will be found in consistency report and
index will not be compared with store.

** Productise GBPTree consistency checker **
Before, the GBPTreeConsistencyChecker was only used as guidance during
development of the GBPTree and for test usages which meant it was find
by simply throwing exceptions whenever it run into something surprising.
A huge part of this PR is about making this consistency checker more
robust and reporting nicely to visitor.

Original commit messages:

commit c3b63dfe0f71361a0be93c3ee0a0cf7d737137d6
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Sep 3 14:54:02 2019 +0200

    Use int to count errors and warnings in FormattingDocumentedHandler

    To avoid potential overflow.

commit 88c72ac8363d7fc6e9a9222b7dbf61a4a84eb767
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Sep 3 14:46:17 2019 +0200

    Cleanup around ReporterFactory

    - Extract @Documented message extraction into DocumentedUtils class
    - Move static ReporterFactory instances to ReporterFactories class
    - Rename static ReporterFactory methods to "Reporter" instead of "Proxy"

commit d42258e69b79c445cdcc81a8fe0accddb06b14e2
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Sep 3 14:25:07 2019 +0200

    Rename ProxyFactory -> ReporterFactory

commit 047c8a6912f434eac7e567053d5a9ae13037172e
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Sep 3 14:17:59 2019 +0200

    Remove zero argument consistencyCheck() from ConsistencyCheckable

commit f0109ae2f50f727ee49cecef27e48ab66f40b6d6
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Aug 30 14:51:17 2019 +0200

    Fix GBPTreeCorruption#overwriteKeyAtPosInternal and #overwriteKeyAtPosLeaf

commit abddcf2daf1d1e7db56e93010e93cdbaa8c6b08f
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Wed Aug 28 16:12:14 2019 +0200

    Addressing PR comments

    - Rename GBPTree#corrupt -> GBPTree#unsafe and introduce GBPTreeUnsafe.
    - Use LongList and ImmutableLongList in InspectingVisitor and
      GBPTreeInspection.
    - Move GBPTreeCorruption to src/test
    - GBPTree#visit take generic visitor and return it instead of presenting
      special GBPTree#inspect.

commit 1d5b89e62c3460988fec1fff826082fb2cba05f6
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 26 15:49:12 2019 +0200

    Fix test failures caused by label index started with no file in read only mode

    Fixed in tests by first starting up db with readOnly=false to setup
    label index and the start up in read only mode.

commit 46db063b3e56fbd6df4beaee639d95978185505e
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 26 14:55:36 2019 +0200

    Rename: MetaToLayoutFactory -> LayoutBootstrapper

commit 5cb55654621384748055a7218bdc5796dc5ff670
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 26 14:27:04 2019 +0200

    Add test for consistency check on fusion index

    Also improve SchemaLayout to be able to bootstrap more schema layouts.

commit 1564a5c244ad96d90bd119c6208e00d278322645
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 26 11:52:14 2019 +0200

    Don't print consistency report in test, verify result is better

commit 479422b3653acc25981e0bd338bb466d805605c4
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 26 10:40:50 2019 +0200

    Small cleanups

commit f909f46d20f51240df01c4b45a7b64758c02bc09
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 26 10:38:30 2019 +0200

    Lucene index also report inconsistency to ProxyFactory

commit 32a6a4487c422a2c5f28f128c136a47b101f1917
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Aug 23 17:00:26 2019 +0200

    Rename: Reporter -> ProxyFactory

    We already have a ProxyFactory in ConsistencyReporter that take class in
    constructor and create proxies from provided InvocationHandler.
    This ProxyFactory does the opposite. Produce proxy for provided class
    that dispatch call to InvocationHandler passed to constructor.
    It's unfortunate that those share name but 'Reporter' is simply worse.

commit 4fbf301ac1a58af70203112531917a6081e64b08
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Aug 23 16:49:58 2019 +0200

    Small cleanups

commit 334fe2fd21c4a52ac20274b601509fae04571dc5
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Aug 23 16:38:10 2019 +0200

    Make GBPTreeConsistencyCheckerTest generic in <KEY,VALUE>

    Also
    - Fix some checkstyle errors

commit e7eab0b049555b89399af7436f4fbbb888ffbfb4
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Aug 23 16:15:17 2019 +0200

    Testing for message propagation from GBPTree to consistency checker

    Improved index inconsistency message:
    - Keep new lines.
    - Indent after new line.
    Also
    - TreeNodeDynamicSize guard for unreasonable key count when checking
      meta consistency.

    Some examples of what report might look like:

    ERROR: Index inconsistency: Sibling pointers misaligned.
        Left siblings view:  {5(4)}-(6)->{281474976710655},
        Right siblings view: {5}<-(4)-{8(4)}.
        Index will be excluded from further consistency checks. Index file: /path/to/schema/index/native-btree-1.0/1/index-1.
    ERROR: Index inconsistency: Broken pointer found in tree node 15, pointerType='left sibling',
        slotA[generation=2147483647, readPointer=7, pointer=7, state=3],
        slotB[generation=0, readPointer=0, pointer=7, state=4].
        Index will be excluded from further consistency checks. Index file: /path/to/schema/index/native-btree-1.0/1/index-1.
    ERROR: Index inconsistency: Pointer (left sibling) in tree node 15 has pointer generation 0, but target node 0 has a higher generation 4.
        Index will be excluded from further consistency checks. Index file: /path/to/schema/index/native-btree-1.0/1/index-1.
    ERROR: Index inconsistency: Expected range for this tree node is
        level: -1 {-1} null ≤ key < null
        level: 0 {16} [String("aa...a27")],entityId=-1 ≤ key < null
        level: 1 {15} [String("a...a27")],entityId=-1 ≤ key < [String("aa...a30")],entityId=-1
        but found [String("aa..a30")],entityId=30 in position 0, with keyCount 4 on page 13.
        Index will be excluded from further consistency checks. Index file: /path/to/schema/index/native-btree-1.0/1/index-1.

commit af12708b52d72499f592bc849e2f74cd72307259
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Aug 22 13:52:17 2019 +0200

    Index inconsistency message include index file

commit c135714bc5a8775c7a84ff42deee01b98583cf89
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Aug 22 10:58:23 2019 +0200

    Test that GBPTree consistency check messages propagate to Neo4j consistency checker

commit 3d84c6907bf36a26718ec446adebf0600cd5c984
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 19 17:10:08 2019 +0200

    Better consistency check messages from GBPTree consistency check

    Implemented by adding handler that do formatting on @Documented string.

    Changed order of visitor arguments to fit string formatting.

commit a5dc0b8078ca0406aeb58db0611c605425ea454f
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 19 14:19:35 2019 +0200

    Connect GBPTreeConsistencyChecker with GBPTreeConsistecyChecker

    GBPTree use CleanTrackingConsistencyCheckVisitor internally to track
    if any calls to the consistency check visitor was made instead of
    every GBPTreeConsistencyCheckVisitor needing to implement it's own
    tracking.

    Introduce GBPTreeBootstrapper used to at least somewhat automatically
    open a GBPTree on existing file. We still need to have some knowledge
    about the expected layout of the index however... which is sad.
    We use SchemaLayouts to do this.
    The reason we cannot simple give a list of all known Layouts (like what
    SchemaLayouts eventually will try to do) is because there is no way for
    us currently to tell GenericLayout with 1 slot apart from a GenericLayout
    with multiple slots. This need to be fixed.

    Introduce ConsistencyCheckWithCorruptGBPTreeIT.

commit 594e5be3b499c2467f1ed89355c521633cffde78
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 19 12:18:45 2019 +0200

    Introduce GBPTree#inspect()

    Which give access to general structure of GBPTree from outside. Useful
    for testing.

commit 943bad6ccaf88d8de45124e34a643224d91083f3
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 19 11:33:30 2019 +0200

    Introduce possibility to inject corruptions into GBPTree from outside

    This is helpful for testing consistency checker from outside.

commit 721c359c21c74107c87890b48d563c220f30f965
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Aug 16 16:47:53 2019 +0200

    Introduce GBPTreeBootstrapper

    Somewhat able to bootstrap a GBPTree given
    - PageCache
    - File
    - MetaToLayoutFactory
    - target layout

commit 799a4410507495fb655b37ab3a1da383f6009fd8
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Aug 16 15:38:03 2019 +0200

    Outline for how to connect Neo4j consistency check report with GBPTree report

commit 53c3aecacb0ce54297a7c6c10f0aa921e1e8f41e
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Aug 15 14:32:31 2019 +0200

    Move Documented annotation to annotation-processors module

commit 094f0154e57b59289e77253c59aeaad3f951b772
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Wed Aug 14 14:45:37 2019 +0200

    Consistency checker report page id exceeding last id

commit 5e456fade41ef63e6c513d082f5fc4f65d26e986
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Wed Aug 14 13:38:35 2019 +0200

    Consistency checker report misdirected sibling pointers

commit 33f1e6f8bd344e2f5613d0d5795ef6b76b2bb662
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Wed Aug 14 13:07:36 2019 +0200

    Consistency checker report misdirected child pointers

commit 7135f17905fd133e31fc2b5e7a442f27d6702bbf
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Wed Aug 14 11:31:40 2019 +0200

    TreeNode#checkMetaConsistency(...) return string indicating inconsistency

    This is necessary because checkMetaConsistency is called within
    shouldRetry() loop.

commit 588131b3b0f90cf3bbf7dd30aff3c06d0fb7b96b
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Wed Aug 14 11:06:35 2019 +0200

    Consistency checker recognize circular reference within traversal stack

    We are traversing down one path in the tree. If we on our way down find
    ourselves back on the same node as we've already seen we abort traversing
    down that path.

    To do this we add knowledge about level and page id to KeyRange which
    was already tracking our way down the tree.

commit 2f511ed56e9ac691474f1b80485bbd8b254bf9a4
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Aug 13 17:04:07 2019 +0200

    Consistency checker report pointer pointing skipping level

commit b0d208e9dd05f1ec8b75cb1bfee7ef2e923e08b6
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Aug 13 16:31:36 2019 +0200

    Consistency checker recognize unreasonable key count in tree node

commit 9816d33f5a828361bbd14fb729def2a138c92725
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Aug 13 16:23:25 2019 +0200

    Consistency checker recognize broken and crashed pointers

    We do asserNoCrashOrBrokenPointerInGSPP in separate shouldRetry() so we
    don't have to use DelayedVisitor.

    Additional changes:
    - If end up at page that is not a tree node or not leaf or internal,
      skip rest of the checks.
    - Only assert key order if keyCount is reasonable.
    - crashed page corruption keeps actual pointer value around, only change
      generation.

commit 42a9228ec0cc88f39bc89a779ec7c05ffba780ba
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Aug 13 13:07:20 2019 +0200

    Consistency checker recognize unused page in file

commit 73f4f8b4a0b1ca257764d0918336e07ea36e262d
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Aug 13 11:46:51 2019 +0200

    Use TreeState instead of stable and unstable generation in CrashGenerationCleanerTest

commit 19f9cdffb5601669939089a5981f9c013c97a9d4
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Aug 13 11:37:29 2019 +0200

    GBPTreeCorruption take TreeState instead of stable and unstable generation

    Also fix outdated assumptions about number of present crash pointers in
    CrashGenerationCleanerTest

commit 8d798426e15b44e17f13f5a92829f1b04945e31c
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Aug 13 10:46:15 2019 +0200

    Consistency checker report extra freelist entries as inconsistency

commit d04add28e93f77b3106ef18653bce944474a0e94
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 12 17:09:31 2019 +0200

    Reworking how IdProvider / Freelist visiting works

    # Consistency checker report missing id in freelist as inconsistency
    Also remove old way of testing this.

    # IdProvider aka. Freelist is now visitable

    # Consistency check of freelist is done by consistency checker itself
    Instead of being left on the outside in GBPTree. This also means we add
    the tree nodes as we traverse the tree instead of going over the tree
    again just to add 'seenIds'.

    # Break out GenerationTarget -> GBPTreeGenerationTarget
    To make use of it when visiting freelist.

    # Fix problem with assertAllIdsOccupied
    The highId would be reported as a missing id even though it should never
    be present.

    # Rework how to visit FreelistIdProvider works
    You now visit the freelist through only one call to visitFreelist using
    IdProviderVisitor.
    This makes it easier to print freelist and it can be visited using the
    normal GBPTreeVisitor.

    # Add generics where needed

commit 8d23af51b1565894fe640411386d6ab6b12ff477
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 12 09:54:08 2019 +0200

    Report tree node meta inconsistencies to visitor

    Also add check for misaligned allocOffset and allocSpace overlapping
    active keys.

commit 180ed69570b0db5cf449a0c86d50d32e7a1df5dd
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Aug 8 15:24:48 2019 +0200

    Key order inconsistencies reported to visitor instead of throwing

    GBPTreeConsistencyCheckVisitor is not generic in KEY.

    Introduce DelayedVisitor that buffer inconsistency reports until
    report() is called which means it can be used inside shouldRetry() loop.
    For now only used for key order inconsistencies.

    Extract KeyRange from GBPTreeConsistencyChecker

    Fix issue in GBPTreeConsistencyChecker where range restrictions where
    not accumulated correctly in childRange. Instead it was simply replaced
    which meant the first restriction would be ignored.

commit 4a6678733bcc114a7c89f15c4ca22dee5a9d3593
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Aug 8 12:14:40 2019 +0200

    Most tree structure inconsistencies reported to visitor instead of throw

    Mid change commit: Compiles but GBPTree consistency check behavior is
    very inconsistent.

    Introduce GBPTreeConsistencyCheckVisitor that can be passed to
    GBPTree.consistencyCheck. All inconsistencies should be reported to this
    visitor instead of the consistency checker throwing directly.

commit d1177a6f4319e4e93e2248c8811e7b77c49ed3f6
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Aug 8 12:08:06 2019 +0200

    From CrashGenerationCleanerTest extract PageCorruption and GSPPType

    Rename GSPPType -> GBPTreePointerType

    Implement a bunch of new corruption variants that will later be used in
    gbptree consistency check test.

commit 34676a8636333b628ed07b810a8a1d917b1a3a04
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Aug 8 12:03:12 2019 +0200

    Implement printNode method in TreeNodeFixedSize

commit 0846073d7ae881853279866b80e4db5dc68c1a8e
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Aug 8 12:02:10 2019 +0200

    Add static method TreeNode.treeNodeType

commit 594ca9ad58549ba4d0bea430141d7d45cd270c85
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 5 15:11:23 2019 +0200

    GBPTreeConsistencyChecker take responsibility of moving Cursor to Root.

commit e62e2595280b7c4bf5abe13a4a28969cf3f2a778
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 5 12:53:28 2019 +0200

    Rename ConsistencyChecker -> GBPTreeConsistencyChecker

commit d45449a916f9347f4be9de8208c2c1d244a00fbd
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Mon Aug 5 11:39:49 2019 +0200

    IndexingService crash db if indexes need rebuild in readOnly mode

    If any indexes need to be rebuilt during db startup, IndexingService
    will crash db. This happens for example if index file is missing or if
    index was not fully populated on last shutdown.

commit f0bea8083b9bd058b8a56b4e1c4f9a25fb4c6044
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Jul 12 15:01:53 2019 +0200

    Read only flag passed down to NativeIndexAccessor and Populator

commit a7e02a1709c97e99052f91c7958047096a0185fb
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Fri Jul 12 14:15:19 2019 +0200

    Label scan store gracefully handles missing file exception from GBPTree

commit a468f13c396ff49a5105d015bc8051364e8d342e
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Tue Jul 2 15:32:07 2019 +0200

    GBPTree can be opened in readOnly mode

commit 2f2693733705a156485b8d3e4eb540224632cd17
Author: Anton Persson <anton.persson@neotechnology.com>
Date:   Thu Jul 11 17:07:09 2019 +0200

    Outline for: Consistency checker remove corrupt indexes before start

    - IndexAccessor extends ConsistencyCheckable