CreateDbTool migrate and upgrade ()
* Extract DbSetup from DbCreator

Extract dbms setup from DbCreator into new DbSetup interface.
This will make it possible to have a DbSetup that unpacks an
existing .zip store and migrate or upgrade instead of creating
a new dbms.

Description used to name homeDirectory, .txt and .zip file is
provided directly by DbDescription instead of as a concatenation
of record format and kernel version.
For custom stores, description can be provided by user using
--description

* ZipUtils can unzip whole sourceZip to targetDirectory

Also inlined
unzip( String sourceZip, Path targetFile ) into
unzipResource( Class<?> klass, String zipName, Path targetFile )

* CreateDbTool has migrate mode

Take existing .zip store and open in current version
with allow_upgrade=true and zip it back down as new
.zip store.

Note! It doesn't do dbms.upgrade().

* CreateDbTool migrate can also upgrade

* Tests for CreateDbTool --migrate

* Address PR comments

- Improve help text
- Correct javadoc for ZipUtils
- Remove left-over print
- Correct test failure description

* Try fix test failure at windows

Can't normalize path that comes from URL.toFile(). Trying to convert to URI instead.

Previous error:
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /Z:/BuildAgent/work/9b7a5724be1663a2/neo4j/private/enterprise/enterprise-it/it-test-support/target/test-classes/com/neo4j/kernel/AF4.1.a_V4.2_empty.zip

* Address PR comments

- Better description for `migrate` mode
- Fix javadoc in ZipUtils