Avoid indirectory relying on commons-lang3.
Not all versions of `MutableInt` have the `decrementAndGet` method.
Using it can thus lead to `NoSuchMethodError` at runtime.
To work around this, we just create our own very minimal Counter class,
which has just the two methods that we actually need, and nothing more.