Add a test to check for duplicate settings
Example output when a duplicate is detected:

    java.lang.AssertionError: 'store.internal_log.rotation_threshold' in store_internal_log_rotation_delay has already been defined in store_internal_log_rotation_threshold