Re-add javax.validation API for Jersey server
It fails to start without it with a NoClassDefFoundError.
Class org.glassfish.jersey.server.model.internal.ResourceMethodInvokerConfigurator
depends on the `javax.validation.Validator` interface from javax validation API.