Migrate cypher-it to Scala 3 and introduce CypherFunSuiteWithMacroShadowing ()
For the actual migration I tried the macro shadowing approach. It gets a
bit fiddly when trying to shadow particularly flowery test assertions,
but at least you don't have to deal with maven exclusions, duplicating
test classes, and then renaming e.g. `ExecutionEngineFunSuite` to
`ExecutionEngineFunSuite3` everywhere. Feel like this results in a
smoother overall experience and gets us to the end goal quicker.

To be fair, there is a downside to this, failed test messages don't
report position correctly:

```
123 did not equal 321
ScalaTestFailureLocation: at (:-1)
Expected :321
Actual   :123
```

But you can find it in the stacktrace:

```
org.scalatest.exceptions.TestFailedException: 123 did not equal 321
	at org.scalatest.matchers.MatchersHelper#.indicateFailure(MatchersHelper.scala:397)
	at org.scalatest.matchers.should.Matchers#AnyShouldWrapper.shouldEqual(Matchers.scala:6876)
	at com.neo4j.internal.cypher.util.comparisonsupport.ConfigsTest.#anonfun#new#1(ConfigsTest.scala:13)
```