Ignore pre-storecopy reconciled IDs in tracker
Seen in test as

```
2019-11-01 10:03:45.838+0000 ERROR [c.n.d.SystemGraphDbmsOperator] Failed to update the last reconciled transaction ID Received illegal transaction ID 21 which is lower than the current transaction ID 22. Sequence: out-of-order-sequence:22 22 []
java.lang.IllegalArgumentException: Received illegal transaction ID 21 which is lower than the current transaction ID 22. Sequence: out-of-order-sequence:22 22 []
        at org.neo4j.util.Preconditions.checkArgument(Preconditions.java:189)
        at org.neo4j.bolt.txtracking.DefaultReconciledTransactionTracker.setLastReconciledTransactionId(DefaultReconciledTransactionTracker.java:110)
        at com.neo4j.dbms.SystemGraphDbmsOperator.updateLastReconciledTransactionId(SystemGraphDbmsOperator.java:92)
        at com.neo4j.dbms.SystemGraphDbmsOperator.lambda#reconcile#0(SystemGraphDbmsOperator.java:55)
        at com.neo4j.dbms.ReconcilerResult.lambda#whenComplete#2(ReconcilerResult.java:66)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture#UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture#AsyncSupply.run(CompletableFuture.java:1705)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor#Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```