Prevent NPE in AbstractSecurityLog#SecurityLogLine formatting ()
While inspecting CI logs i have observed set of NPEs like
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "arg" is null
	at org.neo4j.internal.helpers.Strings.escape(Strings.java:70)
	at org.neo4j.internal.kernel.api.security.AbstractSecurityLog#SecurityLogLine.formatAsString(AbstractSecurityLog.java:259)
	at org.neo4j.logging.log4j.Neo4jMapMessage.appendMap(Neo4jMapMessage.java:50)
	at org.apache.logging.log4j.message.MapMessage.format(MapMessage.java:327)
	at org.apache.logging.log4j.message.MapMessage.formatTo(MapMessage.java:473)
	at org.apache.logging.log4j.core.pattern.MessagePatternConverter#SimpleMessagePatternConverter.format(MessagePatternConverter.java:113)
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44)
	at org.apache.logging.log4j.core.layout.PatternLayout#PatternFormatterPatternSerializer.toSerializable(PatternLayout.java:396)
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:251)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:237)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:227)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:220)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:211)
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:395)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:160)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:807)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:765)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:741)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:685)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:92)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:187)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2970)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2922)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2904)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2337)
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1560)
	at org.neo4j.logging.log4j.Log4jLog.info(Log4jLog.java:83)
	at com.neo4j.server.security.enterprise.log.EnterpriseSecurityLog#MonitoredSecurityLog.info(EnterpriseSecurityLog.java:62)
```

For example, while running AutocommitTransactionRemoteExecutorIT