Prevent race between verifyUniqueness and close in WritableDatabaseSchemaIndex
Verify uniqueness will cause a commit on each IndexWriter tied to the
Lucene partitions.
Close will cause the same IndexWriters to close and try to commit again
because we commit IndexWriter on close (`LiveIndexWriterConfig.getCommitOnClose()`).
Before starting the commit on close however, IndexWriter will verify that
there are no other commits currently running and this is where we throw
exception:
java.lang.IllegalStateException: cannot close: prepareCommit was already
    called with no corresponding call to commit

Now we correctly grab commitCloseLock before we verifyUniqueness.

(Also inlined commitLockedDrop which was never overridden by anyone)