Revert junit bump to 5.3. Restore 5.2.
Because changes introduced as part of https://github.com/junit-team/junit5/issues/1499
new junit is not compatible in a way with surefire test runner and its impossible now to
invoke single test using -Dtest option.

Exception that we get when we do that with new junit version is something like:
java.lang.NoSuchMethodError: org.junit.platform.engine.support.descriptor.MethodSource.from(Ljava/lang/Class;Ljava/lang/reflect/Method;)Lorg/junit/platform/engine/support/descriptor/MethodSource;
 	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.toMethodSource(VintageTestDescriptor.java:155)
 	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.toTestSource(VintageTestDescriptor.java:138)
 	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.<init>(VintageTestDescriptor.java:54)
 	at org.junit.vintage.engine.discovery.TestClassRequestResolver.addChildrenRecursively(TestClassRequestResolver.java:110)
 	at org.junit.vintage.engine.discovery.TestClassRequestResolver.createCompleteRunnerTestDescriptor(TestClassRequestResolver.java:93)
 	at org.junit.vintage.engine.discovery.TestClassRequestResolver.determineRunnerTestDescriptor(TestClassRequestResolver.java:64)
 	at org.junit.vintage.engine.discovery.TestClassRequestResolver.createRunnerTestDescriptor(TestClassRequestResolver.java:59)